/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_teng_androidfactory_JniTest */

#ifndef _Included_com_teng_androidfactory_JniTest
#define _Included_com_teng_androidfactory_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_teng_androidfactory_JniTest
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_teng_androidfactory_JniTest_getJniString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
